# Generated by Django 5.1.4 on 2025-01-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_email_varified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_varified',
        ),
    ]
